### ISSUE TITLE
tmux image persistence

### ISSUE THREAD

**Issue by falsified** [jstkdng/ueberzugpp#15]
I am not 100% sure this is an ueberzugpp issue, but I think it is.

I switched over to kitty a few months ago since ueberzug died, and now kitty is having some integration issues with vifm preview in the latest versions. I found your fork and was super excited since I enjoy tmux more than kitty. I did  however find an issue, if this is not an ueberzug issue,  please let me know..

I am using tmux for an essentially tabbed window, however, when i switch 'windows' on tmux, the image overlay remains
see attached

![blah](https://user-images.githubusercontent.com/20657172/221765193-51cc5834-80c7-4c0e-90d7-a0b1cb9ee785.jpg)

i know that when the original version of ueberzug was working, it cleared the image on change of the screen/terminal. 

any advice or suggestions would be appreciated!

also, thank you so much for taking the torch on!

**Comment by jstkdng** [comment]
hello, yeah this is an issue with ueberzugpp. Right now it's not responding to tmux changes. That's next on the roadmap.

**Comment by falsified** [comment]
great, looking forward to the updates! thanks again!!

**Comment by jstkdng** [comment]
should be fixed on v2.5.0, please do test.

**Comment by mindhuntr** [comment]
I am using tmux version 3.4 and ueberuzgpp version 2.9.4. The persistence issue still occurs with the ranger file manager. 

![2024-04-17_09-27](https://github.com/jstkdng/ueberzugpp/assets/107744570/5bc932d7-0e74-4979-a768-bde882e8a166)
