### ISSUE TITLE
Execute windows rules before creating wayland windows

### ISSUE THREAD

**Issue by HenningCode** [jstkdng/ueberzugpp#207]
Hello,

sorry if this is already answered anywhere, but I cloud not find anything. 
I am using Alacritty with Überzeug++ to preview images and it works flawlessly, but the images are "flying in" as some sort of animation. How can I turn this animation off? 

Greetings

**Comment by jstkdng** [comment]
Are you perhaps using wayland?

**Comment by HenningCode** [comment]
@jstkdng yeah I am on hyprland with wayland.

**Comment by jstkdng** [comment]
i knew it, those "animations" aren't really animations. U++ just creates wayland windows with an image and then moves them by using the wm's rules. Only way to fix that would be to first create the rules and then the windows but that'd need some more complex changes.

**Comment by BEST8OY** [comment]
@HenningCode 
This rule somehow alleviate it but the flying is still there.
```
windowrulev2 = noanim, title:ueberzugpp
```

**Comment by thatDudo** [comment]
Maybe we could create the window one time and then make the window update its shown image through a socket.

**Comment by HenningCode** [comment]
> @HenningCode This rule somehow alleviate it but the flying is still there.
> 
> ```
> windowrulev2 = noanim, title:ueberzugpp
> ```

Sorrt for the late replay. This kind of works, but the images are sometimes rendered in the middle of the screen first. So I think this but is still present?

**Comment by HenningCode** [comment]
@jstkdng 
Another problem is that the created ueberzug windows are not moved accordingly if a pdf is opened.
This example pdf was opened with yazi. 
![image](https://github.com/user-attachments/assets/4bd1d11e-38b1-489c-825e-e43113218e41)

**Comment by HenningCode** [comment]
@jstkdng 

Hi, 
I just wanted to try it, but could not get it running. I am using NixOS and pulling from source and building did not work because I could not manage to get the third_party libs running. CMake states that it cant find the cmaelists.txt of glaze, cli11 and spdlog. 

I saw in this repos cmakelists that its possible to use the library as system library. 
https://github.com/jstkdng/ueberzugpp/blob/master/CMakeLists.txt#L58

Would this be possible for ueberzugpp-new as well? I think than it would be possible for me to build it on nixos and tests it.

**Comment by jstkdng** [comment]
sure, run cmake with the option `-DUSE_BUNDLED_LIBRARIES=OFF` and cmake will try to find the system libraries, or git clone the submodules

**Comment by jstkdng** [comment]
>It's so fast that I didn't know it could actually be this fast

it is indeed fast, and I believe it can be faster

>The only problem I faced is

yeah, the current solution is not robust enough and covers the simplest cases

**Comment by HenningCode** [comment]
@jstkdng I did some more testing and found that very few images are working. So ueberzugpp_new is doing something, but a lot of pictures are not working and pdf are not working at all.

**Comment by jstkdng** [comment]
hm, that is weird, it should work fine unless yazi is doing something else on its side. I'll try to test yazi and see what's going on.

**Comment by jstkdng** [comment]
@HenningCode I think it should be fixed now on master, please do test. Also, noticed yazi resizes the images before sending them to `upp`, you might want to disable that since your pc would be doing double work.

**Comment by jstkdng** [comment]
@BEST8OY that issue should also be fixed now, `upp-new` now responds to terminal size changes

**Comment by HenningCode** [comment]
@jstkdng Some more pictures are loading, still not all. Also pdfs are not working at all.

**Comment by jstkdng** [comment]
@HenningCode are you using the latest commit? pdfs work on my machine :tm:

![Image](https://github.com/user-attachments/assets/f2ec7a42-8ac1-4b08-9a97-65306af3dea4)

**Comment by HenningCode** [comment]
Yes I am. Just tested with commit 98d26e0e278fc0137d385e9666b2a13024946401.

For me its not working.. 

![Image](https://github.com/user-attachments/assets/5f65ccac-0c3b-4d23-9908-0cc93cdc6a2a)

Can I somehow better debug why this could not be working?

**Comment by jstkdng** [comment]
>Can I somehow better debug why this could not be working?

sure, run `export SPDLOG_LEVEL=trace`, try to show pdfs, and then post the log at `/tmp/ueberzugpp-$USER.log`

**Comment by HenningCode** [comment]
[ueberzugpp-henning.log](https://github.com/user-attachments/files/18784056/ueberzugpp-henning.log)

Okay this is a log. I selected images that work and pdfs and images that dont work. The ones working dont have these log messages 

```
[2025-02-13 13:50:41.482674122] [I] [vips] resizing image 8de3aa838465b8d4ba58c9358f4c3b97 to 440x236 and caching
[2025-02-13 13:50:41.799619189] [I] [application] starting
```

**Comment by jstkdng** [comment]
Hmmm, only INFO messages are being logged, seems SPDLOG_LEVEL is not reaching `upp`. Can you test on other file managers?

**Comment by HenningCode** [comment]
@jstkdng I just tested it with ranger now. Pictures are all getting shown now, but PDFs still no good. Also when using ranger no logs were created. I dont really know why...

And I found another bug while in tmux. Pictures not not getting drawn in the right place. 

![Image](https://github.com/user-attachments/assets/9d1ecaca-8b2f-4dbb-9c9f-369b62683c9a)

**Comment by BEST8OY** [comment]
This is indeed weird
I'm getting pdf pictures with lf and alacritty+yazi

![Image](https://github.com/user-attachments/assets/1e132951-33e8-4ea6-a6a1-80bc07f77308)

**Comment by jstkdng** [comment]
>I just tested it with ranger now

pdfs don't show with ranger afaik

>And I found another bug while in tmux. Pictures not not getting drawn in the right place.

tmux is not yet implemented

>when using ranger no logs were created

maybe ranger is overriding TMP_DIR or something under nixos

**Comment by HenningCode** [comment]
Okay I just checked it with my Arch install I still had. There it works fine with yazi. Everything shows up. Seems to be an install issue from my side on nixos. Any ideas whentmux support will come?

**Comment by jstkdng** [comment]
>Seems to be an install issue from my side on nixos

weird that it only happens with nixos

>Any ideas whentmux support will come?

probably after gif support

**Comment by emphs** [comment]
just tried switch to ueberzugpp-new-git on hyprland yazi arch, not showing any image/pdf

```Elixir
 _   _      _
| | | |    | |                                _     _
| | | | ___| |__   ___ _ __ _____   _  __ _ _| |_ _| |_
| | | |/ _ \ '_ \ / _ \ '__|_  / | | |/ _` |_   _|_   _|   version: 0.0.1 (None build)
| |_| |  __/ |_) |  __/ |   / /| |_| | (_| | |_|   |_|     build date: 2025-08-24T21:05:14Z
 \___/ \___|_.__/ \___|_|  /___|\__,_|\__, |
                                       __/ |    new
                                      |___/
[2025-08-24 13:20:28.633804487] [I] [application] TERM = xterm-256color
[2025-08-24 13:20:28.633818142] [I] [application] TERM_PROGRAM = ghostty
[2025-08-24 13:20:28.634205978] [I] [X11] connected to Xwayland
[2025-08-24 13:20:28.634212280] [I] [hyprland] using socket /run/user/1000/hypr/f58bb72d3a300dc482e9dc934101790c8707667d_1754887757_1303694042/.socket.sock
[2025-08-24 13:20:28.634295916] [I] [hyprland] version: 0.49.0
[2025-08-24 13:20:28.634450656] [I] [terminal] PTY = /dev/pts/1
[2025-08-24 13:20:28.634452920] [I] [terminal] PID = 397334
[2025-08-24 13:20:28.635184669] [I] [wayland] canvas created
[2025-08-24 13:20:28.635190880] [I] [listener] using json parser
[2025-08-24 13:20:28.635238529] [I] [listener] listening for commands on stdin
[2025-08-24 13:20:28.635333998] [I] [listener] listening for commands on socket /tmp/ueberzugpp-454974.socket
[2025-08-24 13:20:43.970049375] [W] [application] received SIGHUP, terminating
[2025-08-24 13:20:43.970109387] [I] [application] ueberzugpp terminated
[2025-08-24 13:20:43.970160913] [W] [listener] could not wait for data from stdin: poll received POLLHUP
[2025-08-24 13:20:44.070641065] [W] [listener] could not wait for data from socket: poll received POLLNVAL
```
uhm not quit sure what happened from /tmp/ueberzugpp-$USER.log
